version: 2.1

orbs: 
  docker: circleci/docker@2.1.1

executors:
  linux-default-runner:
    machine: true
    resource_class: navi86/default

  
workflows:
  my-workflow:
    jobs:
      - my-job

jobs:
  my-job:
    executor: linux-default-runner
    steps:
      - checkout
      - run: echo "Hello from my custom runner!. From feature branch"
      - docker/build:
          image: '$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME'
          cache_from: '$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest'
          tag: latest
          path: image
          docker-context: image
      - run: sleep 900000
  